# Generated by Django 5.0.6 on 2024-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street',
            old_name='end_number',
            new_name='altura_final',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='start_number',
            new_name='altura_inicial',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='street',
            name='coordenadas_finales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='coordenadas_iniciales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='es_avenida',
            field=models.BooleanField(default=False),
        ),
    ]
